In [3]:
import numpy as np
import random
random.randint(0,100)

23

In [4]:
import numpy as np
print("Números aleatorios entre [0,1) de tamaño  2,2")
print(np.random.rand(3,5))

Números aleatorios entre [0,1) de tamaño  2,2
[[0.75812831 0.86762007 0.45839544 0.07459292 0.41329088]
 [0.1265607  0.02408987 0.03796617 0.98770602 0.83438014]
 [0.91126124 0.80909522 0.72326253 0.81632952 0.49958884]]


In [5]:
print("Números aleatorios de una distribución normal con media=0 y varianza=1 de tamaño 2,2")
print(np.random.randn(2,2))

Números aleatorios de una distribución normal con media=0 y varianza=1 de tamaño 2,2
[[ 0.36566806  0.66322197]
 [-0.77217207  0.18420271]]


In [6]:
print("Enteros aleatorios entre [0,100) de tamaño 5,5")
print(np.random.randint(0, 100, size=[5,5]))

Enteros aleatorios entre [0,100) de tamaño 5,5
[[46 17 85 10  3]
 [ 9 79 91 27  2]
 [76 56 58 75 61]
 [86 34 11 27 44]
 [49 20 42 62 41]]


In [7]:
print("Genera un número aleatorio entre [0,1)")
print(np.random.random())

Genera un número aleatorio entre [0,1)
0.8714962337190547


In [8]:
print("Elige 10 elementos de una lista (los resultados son equiprobables)")
print(np.random.choice(['Cara', 'Sol'], size=10))

Elige 10 elementos de una lista (los resultados son equiprobables)
['Sol' 'Cara' 'Sol' 'Sol' 'Cara' 'Cara' 'Sol' 'Cara' 'Cara' 'Sol']


In [9]:
# ponemos una semilla 100 para reproducibilidad
np.random.seed(100)
print(np.random.rand(2,2))

[[0.54340494 0.27836939]
 [0.42451759 0.84477613]]


In [10]:
np.random.seed(1)
arr_rand = np.random.randint(0, 10, size=100)
arr_rand

array([5, 8, 9, 5, 0, 0, 1, 7, 6, 9, 2, 4, 5, 2, 4, 2, 4, 7, 7, 9, 1, 7,
       0, 6, 9, 9, 7, 6, 9, 1, 0, 1, 8, 8, 3, 9, 8, 7, 3, 6, 5, 1, 9, 3,
       4, 8, 1, 4, 0, 3, 9, 2, 0, 4, 9, 2, 7, 7, 9, 8, 6, 9, 3, 7, 7, 4,
       5, 9, 3, 6, 8, 0, 2, 7, 7, 9, 7, 3, 0, 8, 7, 7, 1, 1, 3, 0, 8, 6,
       4, 5, 6, 2, 5, 7, 8, 4, 4, 7, 7, 4])

In [11]:
vals_unicos, frecuencias = np.unique(arr_rand, return_counts=True)
print("Elementos únicos: ", vals_unicos)
print("Frecuencias      :", frecuencias)

Elementos únicos:  [0 1 2 3 4 5 6 7 8 9]
Frecuencias      : [ 9  8  7  8 11  7  8 18 10 14]
